# Gradle
org.gradle.jvmargs=-Xmx1G
org.gradle.parallel=true
# IntelliJ IDEA is not yet fully compatible with configuration cache, see: https://github.com/FabricMC/fabric-loom/issues/1349
org.gradle.configuration-cache=false

# Fabric Properties
# check these on https://fabricmc.net/develop
minecraft_version=26.3
loader_version=0.19.5
loom_version=1.18.2

# Mod Properties
mod_version=1.3.1+mc26.3
maven_group=com.makev1ch
archives_base_name=freecursor

# Dependencies
fabric_api_version=0.161.0+26.3
fabric_keymapping_version=2.0.8+3434d6d95d
